name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"


      - name: Restore
        run: dotnet restore Day4/Task1/Day3.csproj

      - name: Build
        run: dotnet build Day4/Task1/Day3.csproj --no-restore

      - name: Test (Unit)
        run: |
          dotnet test Day4/Task1/Quotes.Tests.Unit/Quotes.Tests.Unit.csproj --no-build \
            --logger "trx;LogFileName=test-results-unit.trx" \
            --collect:"XPlat Code Coverage"

      - name: Test (Integration)
        run: |
          dotnet test Day4/Task1/IntegrationTests/Day3.IntegrationTests.csproj --no-build \
            --logger "trx;LogFileName=test-results-integration.trx" \
            --collect:"XPlat Code Coverage"
          dotnet test Day4/Task1/Quotes.Tests.Integration/Quotes.Tests.Integration.csproj --no-build \
            --logger "trx;LogFileName=test-results-integration2.trx" \
            --collect:"XPlat Code Coverage"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/*.trx"

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: "**/coverage.cobertura.xml"